language: node_js
node_js:
    - 12
os:
    - linux

services:
    - docker

before_install:
    - docker run -d --name postgres_container -p 5432:5432 postgres

install: true

script:
    - npm install
    - npm run test
