sudo: required
language: node_js

node_js:
  - 12

os:
  - linux

cache:
  directories:
    - node_modules

services:
  - docker

branches:
  except:
    - develop
    - /^feature/\d+\.\d+$/
  only:
    - master

before_install:
  - docker run -d --name postgres_container -p 5432:5432 postgres
  - npm update

install:
  - npm install

script:
  - yarn coveralls


