sudo: required
language: node_js

node_js:
  - 12

os:
  - linux

services:
  - docker

branches:
  except:
    - develop
    - /^feature/DCLI-\d+\.\d+$/
  only:
    - master

#before_install:
 # - docker run -d --name postgres_container -p 5432:5432 postgres

install:
  - npm install

#script:
#  - yarn coveralls

before_deploy:
  - npm --no-git-tag-version version patch

deploy:
  edge: true
  provider: npm
  email: "enesusta@protonmail.com"
  api_key: $NPM_API_KEY
  skip_cleanup: true
